### ISSUE TITLE
Error met when using multi nodes

### ISSUE THREAD

**Issue by Lechatelia** [microsoft/tutel#61] opened 2021-12-23 04:53 UTC
Dear contributors, 
 I meet an error with tutel's moe layer.
The error occurred when I run the  `tutel/examples/helloworld_ddp.py` in the torch distributed mode with more than one GPU node (i.e.: 16 GPUs on 2 machines).
However, It is fine when I run this script with  8 GPUs or less. 

The error log is  following:
```

[Benchmark] world_size = 16, dtype = float32, model_dim = 2048, hidden_size = 2048, samples = 65536, num_local_experts = 2, topK = 1, device = `cuda:0`
Traceback (most recent call last):
  File "tutel/examples/helloworld_ddp.py", line 154, in <module>
    output = model(x)
  File "/mnt/cache/zhujinguo/anaconda3/envs/xmodaler/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/mnt/cache/zhujinguo/anaconda3/envs/xmodaler/lib/python3.7/site-packages/torch/nn/parallel/distributed.py", line 705, in forward
    output = self.module(*inputs[0], **kwargs[0])
  File "/mnt/cache/zhujinguo/anaconda3/envs/xmodaler/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "tutel/examples/helloworld_ddp.py", line 119, in forward
    result = self._moe_layer(input)
  File "/mnt/cache/zhujinguo/anaconda3/envs/xmodaler/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/mnt/lustre/zhujinguo/codes/tutel/tutel/impls/moe_layer.py", line 387, in forward
    result_output, l_aux = self.gate.apply_on_expert_fn(reshaped_input, self.expert_fn, self.group)
  File "/mnt/lustre/zhujinguo/codes/tutel/tutel/impls/moe_layer.py", line 103, in apply_on_expert_fn
    locations1 = self.compute_location(masks_se[0])
  File "/mnt/lustre/zhujinguo/codes/tutel/tutel/jit_kernels/gating.py", line 81, in fast_cumsum_sub_one
    return get_cumsum_kernel(data.size(0), data.size(1))(data)
  File "/mnt/lustre/zhujinguo/codes/tutel/tutel/jit_kernels/gating.py", line 72, in optimized_cumsum
    base_kernel(mask1.to(torch.int32).contiguous(), locations1)
  File "/mnt/lustre/zhujinguo/codes/tutel/tutel/impls/jit_compiler.py", line 39, in func
    tutel_custom_kernel.invoke_with_source(inputs, __ctx__, no_nvrtc, source)
RuntimeError: (0) == (cuModuleGetFunction(&gm.hFunc, gm.hMod, std::string(pos, tail - pos).c_str())) INTERNAL ASSERT FAILED at "/mnt/lustre/zhujinguo/codes/tutel/tutel/custom/custom_kernel.cpp":208, please report a bug to PyTorch. CHECK_EQ fails.

```

Also, I use tutel moe layer in another project, where the same thing happened.

**Comment by ghostplant** [comment] 2021-12-23 12:48
Can you try `export NO_NVRTC=0` or `export NO_NVRTC=1` to see which one works?
BTW, can you provide the version (or commit point) you encounter this issue?

**Comment by Lechatelia** [comment] 2021-12-23 14:07
Thanks for your ansewer.
Unfortunately, none of them (`export NO_NVRTC=0` and `export NO_NVRTC=1`) works for me. 
The commit point is cd09895a7c1c813ed926d263e99267a4eefbf67f.

**Comment by ghostplant** [comment] 2021-12-23 14:57
Cannot reproduce this issue. Can you paste each command you execute on 2 nodes?

For reference:
```sh
ssh <node-ip-0> python3 -m torch.distributed.launch --use_env --nproc_per_node=8 --nnodes=2 --node_rank=0 --master_addr=<node-ip-0> --master_port=14235 <absolute_path_to_tutel_helloworld>
ssh <node-ip-1> python3 -m torch.distributed.launch --use_env --nproc_per_node=8 --nnodes=2 --node_rank=1 --master_addr=<node-ip-0> --master_port=14235 <absolute_path_to_tutel_helloworld>
```

**Comment by Lechatelia** [comment] 2021-12-23 16:11
Thank you!
I have solved this problem by upgrading to `torch1.10+cuda11.1`.

And `export NO_NVRTC=0` is also needed.

**Comment by ghostplant** [comment] 2021-12-23 16:22
Thank you for your information. I'll just close this issue if it is fixed.

**Closed by ghostplant** 2021-12-23 16:22 UTC
